version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: subha
      MYSQL_PASSWORD: subha
      MYSQL_DB: two-tier
    depends_on:
      - mysql
 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:  test@123
      MYSQL_USER: subha
      MYSQL_PASSWORD: subha
      MYSQL_DATABASE: two-tier
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:




